language: node_js
node_js:
  - 12
branches:
  only:
    - master
cache:
  directories:
    - node_modules
env: >
  NODE_ENV=production
  APP_NAME='Dota Card Game Api'
  APP_VERSION='1.0.0'
  DB_PORT='3306'
  DB_HOST='remotemysql.com'
  DB_NAME='8fboJ1HdkT'
  DB_USER='8fboJ1HdkT'
  DB_PASSWORD='k1XNr1pcb9'

before_script:
  - cp .env.example .env
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
