language: node_js
node_js:
  - 12
branches:
  only:
    - master

env: >
  NODE_ENV=production
  APP_NAME='Dota Card Game Api'
  APP_VERSION='1.0.0'
  APP_PORT='80'
  APP_HOST='127.0.0.1'
  APP_URL='http://localhost:80'

before_script:
  - cp .env.example .env

script:
  - npm start
