language: node_js
node_js:
  - 12
branches:
  only:
    - master

env: >
  NODE_ENV=production
  APP_NAME='Dota Card Game Api'
  APP_VERSION='1.0.0'

before_script:
  - cp .env.example .env
  - npm install
script:
  - npm run build
