language: node_js
node_js:
  - 12
branches:
  only:
    - master
cache:
  directories:
    - node_modules
env: >
  NODE_ENV=production
  APP_NAME='Dota Card Game Api'
  APP_VERSION='1.0.0'

before_script:
  - npm install
  - cp .env.example .env
script:
  - npm run build:prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
